// Code generated by admin-gen. DO NOT EDIT.
package admin

import (
	"encoding/json"
	"errors"

	"github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
	"gorm.io/gorm"

	"github.com/hokkung/go-admin/admin-gen/runtime"
	"github.com/hokkung/go-admin/example/cmd/admin-gen/models"
)

// ProductHandler serves POST /product.<action> routes backed by GORM.
// One-file-per-entity by design: handlers, routing, and filter/sort
// allowlists live together so you can trace a request end-to-end in a single
// tab.
type ProductHandler struct {
	db *gorm.DB
	// idGenerator mints an id when create is called with the zero value.
	// Default is nil (DB auto-increment) except for UUID entities, where
	// the constructor seeds it with uuid.New so existing behavior is
	// preserved. Override via SetIDGenerator.
	idGenerator func() uuid.UUID
	// actions holds fiber handlers for //admin:action-declared custom
	// actions, keyed by action name. Populated at runtime via OnAction.
	actions map[string]fiber.Handler
}

func NewProductHandler(db *gorm.DB) *ProductHandler {
	return &ProductHandler{
		db:          db,
		idGenerator: func() uuid.UUID { return uuid.New() },
		actions:     map[string]fiber.Handler{},
	}
}

// SetIDGenerator installs a custom id minter. Called after construction, it
// overrides the default uuid.New seed. The
// function runs only when create receives a zero-valued id, so clients that
// pass their own id still win.
func (h *ProductHandler) SetIDGenerator(fn func() uuid.UUID) {
	h.idGenerator = fn
}

// OnAction wires a fiber handler to a //admin:action-declared action name.
// Panics on unknown names so typos fail loud at startup rather than as a
// 501 on the first client request.
func (h *ProductHandler) OnAction(name string, handler fiber.Handler) {
	if _, ok := productKnownActions[name]; !ok {
		panic("product: unknown custom action " + name + " (declared actions: see //admin:action directives above " + "Product)")
	}
	h.actions[name] = handler
}

// Register mounts all product.* routes onto the given router.
func (h *ProductHandler) Register(r fiber.Router) {
	r.Post("/product.create", h.create)
	r.Post("/product.get", h.get)
	r.Post("/product.update", h.update)
	r.Post("/product.delete", h.delete)
	r.Post("/product.list", h.list)
	r.Post("/product.metadata", h.metadata)
	r.Post("/product.purge", h.dispatchAction("purge"))
}

// dispatchAction looks up the handler registered for name via OnAction and
// returns 501 NOT_IMPLEMENTED if the caller forgot to wire one up.
func (h *ProductHandler) dispatchAction(name string) fiber.Handler {
	return func(c *fiber.Ctx) error {
		handler, ok := h.actions[name]
		if !ok {
			return runtime.WriteError(c, runtime.NotImplemented(name))
		}
		return handler(c)
	}
}

// productKnownActions is the set of declared custom actions for this
// entity, used by OnAction to reject typos. Generated from //admin:action
// directives.
var productKnownActions = map[string]struct{}{
	"purge": {},
}

// ---- create -----------------------------------------------------------

func (h *ProductHandler) create(c *fiber.Ctx) error {
	var entity models.Product
	if len(c.Body()) > 0 {
		if err := json.Unmarshal(c.Body(), &entity); err != nil {
			return runtime.WriteError(c, runtime.BadRequest("invalid json: "+err.Error()))
		}
	}

	if h.idGenerator != nil && isZeroProductID(entity.ID) {
		entity.ID = h.idGenerator()
	}

	if err := validateProduct(&entity); err != nil {
		return runtime.WriteError(c, runtime.ValidationError(err))
	}

	if err := h.db.WithContext(c.Context()).Create(&entity).Error; err != nil {
		return runtime.WriteError(c, err)
	}
	return c.JSON(entity)
}

// ---- get --------------------------------------------------------------

func (h *ProductHandler) get(c *fiber.Ctx) error {
	id, err := decodeProductID(c.Body())
	if err != nil {
		return runtime.WriteError(c, err)
	}
	var entity models.Product
	if err := h.db.WithContext(c.Context()).First(&entity, "\"id\" = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return runtime.WriteError(c, runtime.ErrNotFound)
		}
		return runtime.WriteError(c, err)
	}
	return c.JSON(entity)
}

// ---- update (partial merge: read, overlay, write) ---------------------

func (h *ProductHandler) update(c *fiber.Ctx) error {
	var raw map[string]json.RawMessage
	if len(c.Body()) > 0 {
		if err := json.Unmarshal(c.Body(), &raw); err != nil {
			return runtime.WriteError(c, runtime.BadRequest("invalid json: "+err.Error()))
		}
	}
	idRaw, ok := raw["id"]
	if !ok {
		return runtime.WriteError(c, runtime.BadRequest("id is required"))
	}
	id, err := decodeProductIDFromRaw(idRaw)
	if err != nil {
		return runtime.WriteError(c, err)
	}

	var entity models.Product
	if err := h.db.WithContext(c.Context()).First(&entity, "\"id\" = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return runtime.WriteError(c, runtime.ErrNotFound)
		}
		return runtime.WriteError(c, err)
	}

	delete(raw, "id")
	rebuilt, mErr := json.Marshal(raw)
	if mErr != nil {
		return runtime.WriteError(c, runtime.BadRequest("invalid update body"))
	}
	if err := json.Unmarshal(rebuilt, &entity); err != nil {
		return runtime.WriteError(c, runtime.BadRequest("invalid update body: "+err.Error()))
	}
	entity.ID = id

	if err := validateProduct(&entity); err != nil {
		return runtime.WriteError(c, runtime.ValidationError(err))
	}

	if err := h.db.WithContext(c.Context()).Save(&entity).Error; err != nil {
		return runtime.WriteError(c, err)
	}
	return c.JSON(entity)
}

// ---- delete -----------------------------------------------------------

func (h *ProductHandler) delete(c *fiber.Ctx) error {
	id, err := decodeProductID(c.Body())
	if err != nil {
		return runtime.WriteError(c, err)
	}
	tx := h.db.WithContext(c.Context()).Delete(&models.Product{}, "\"id\" = ?", id)
	if tx.Error != nil {
		return runtime.WriteError(c, tx.Error)
	}
	if tx.RowsAffected == 0 {
		return runtime.WriteError(c, runtime.ErrNotFound)
	}
	return c.JSON(fiber.Map{"deleted": true, "id": id})
}

// ---- list (filter / sort / paginate, all pushed into SQL) -------------

func (h *ProductHandler) list(c *fiber.Ctx) error {
	var q runtime.ListQuery
	if len(c.Body()) > 0 {
		if err := json.Unmarshal(c.Body(), &q); err != nil {
			return runtime.WriteError(c, runtime.BadRequest("invalid json: "+err.Error()))
		}
	}
	runtime.NormalizeQuery(&q, 20, 100)

	tx := h.db.WithContext(c.Context()).Model(&models.Product{})

	for _, f := range q.Filters {
		switch f.Field {
		case "name", "price", "status", "user_ids", "created_at", "updated_at", "deleted_at":
			tx = runtime.ApplyGormFilter(tx, f.Field, f)
		default:
			return runtime.WriteError(c, runtime.BadRequest("field not filterable: "+f.Field))
		}
	}

	var total int64
	if err := tx.Session(&gorm.Session{}).Count(&total).Error; err != nil {
		return runtime.WriteError(c, err)
	}

	for _, s := range q.Sort {
		switch s.Field {
		case "name", "price", "stock", "created_at", "updated_at", "deleted_at":
			dir := "ASC"
			if s.Order == "desc" {
				dir = "DESC"
			}
			tx = tx.Order("\"" + s.Field + "\" " + dir)
		default:
			return runtime.WriteError(c, runtime.BadRequest("field not sortable: "+s.Field))
		}
	}

	var items []models.Product
	if err := tx.Offset((q.Page - 1) * q.PageSize).Limit(q.PageSize).Find(&items).Error; err != nil {
		return runtime.WriteError(c, err)
	}
	return c.JSON(runtime.ListResult[models.Product]{
		Items:    items,
		Total:    int(total),
		Page:     q.Page,
		PageSize: q.PageSize,
	})
}

// ---- metadata ---------------------------------------------------------

// productMetadataBase holds the shape of this entity as computed at
// generation time. BuildMetadata clones it per request and stamps the
// request-absolute Path / MetadataPath so clients see absolute URLs that
// work regardless of how the admin routes are grouped.
var productMetadataBase = runtime.Metadata{
	Name:        "product",
	DisplayName: "Product",
	PrimaryKey:  "id",
	Fields: []runtime.FieldMetadata{
		{Name: "id", Type: "string", Primary: true, Readonly: true},
		{Name: "name", Type: "string", Filterable: true, Sortable: true},
		{Name: "price", Type: "float", Filterable: true, Sortable: true},
		{Name: "stock", Type: "int", Sortable: true},
		{Name: "status", Type: "object", Filterable: true},
		{Name: "user_ids", Type: "object", Filterable: true},
		{Name: "created_at", Type: "datetime", Readonly: true, Filterable: true, Sortable: true},
		{Name: "updated_at", Type: "datetime", Readonly: true, Filterable: true, Sortable: true},
		{Name: "deleted_at", Type: "object", Readonly: true, Filterable: true, Sortable: true},
		{Name: "metadata", Type: "object"},
	},
	Actions: runtime.ActionsMetadata{
		Standard: []string{"list", "get", "create", "update", "delete", "metadata"},
		Custom: []runtime.CustomAction{
			{Name: "purge", Destructive: true},
		},
	},
	ListConfig: runtime.ListConfig{
		DefaultPageSize: 20,
		MaxPageSize:     100,
	},
}

// BuildMetadata returns this entity's metadata with Path / MetadataPath
// filled in relative to base (see runtime.RequestBase). Exported so the
// shared admin.entities catalog can aggregate without reflection.
func (h *ProductHandler) BuildMetadata(base string) runtime.Metadata {
	m := productMetadataBase
	m.Path = base + "product.list"
	m.MetadataPath = base + "product.metadata"
	return m
}

func (h *ProductHandler) metadata(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{"data": h.BuildMetadata(runtime.RequestBase(c))})
}

// ---- validation -------------------------------------------------------

// validateProduct runs every admin-layer check against e in the order
// the runtime admin package uses: enum allowlists first, then each field's
// Validator (both value and pointer form), then the entity's Validator.
// Non-nil returns become the VALIDATION_FAILED envelope.
func validateProduct(e *models.Product) error {
	if err := runtime.CallFieldValidator("id", e.ID, &e.ID); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("name", e.Name, &e.Name); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("price", e.Price, &e.Price); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("stock", e.Stock, &e.Stock); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("status", e.Status, &e.Status); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("user_ids", e.UserIDs, &e.UserIDs); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("created_at", e.CreatedAt, &e.CreatedAt); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("updated_at", e.UpdatedAt, &e.UpdatedAt); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("deleted_at", e.DeletedAt, &e.DeletedAt); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("metadata", e.Metadata, &e.Metadata); err != nil {
		return err
	}
	if err := runtime.CallEntityValidator(*e, e); err != nil {
		return err
	}
	return nil
}

// ---- id decoding ------------------------------------------------------

type productIDBody struct {
	ID uuid.UUID `json:"id"`
}

func decodeProductID(body []byte) (uuid.UUID, error) {
	var req productIDBody
	if len(body) == 0 {
		return req.ID, runtime.BadRequest("id is required")
	}
	if err := json.Unmarshal(body, &req); err != nil {
		return req.ID, runtime.BadRequest("invalid id: " + err.Error())
	}
	if isZeroProductID(req.ID) {
		return req.ID, runtime.BadRequest("id is required")
	}
	return req.ID, nil
}

func decodeProductIDFromRaw(raw json.RawMessage) (uuid.UUID, error) {
	var id uuid.UUID
	if len(raw) == 0 {
		return id, runtime.BadRequest("id is required")
	}
	if err := json.Unmarshal(raw, &id); err != nil {
		return id, runtime.BadRequest("invalid id: " + err.Error())
	}
	return id, nil
}

func isZeroProductID(id uuid.UUID) bool {
	return id == uuid.Nil
}
