// Code generated by admin-gen. DO NOT EDIT.
package admin

import (
	"github.com/gofiber/fiber/v2"
	"gorm.io/gorm"

	"github.com/hokkung/go-admin/admin-gen/runtime"
)

// Admin bundles every generated entity handler. Construct it with Register,
// then call Mount to attach the routes to your fiber app or a sub-router.
type Admin struct {
	Product *ProductHandler
	Session *SessionHandler
	User    *UserHandler
}

// Register wires up every admin entity against the shared *gorm.DB. Exposing
// each handler on the returned struct lets callers swap, wrap, or hand-edit
// any single entity without disturbing the rest.
func Register(db *gorm.DB) *Admin {
	return &Admin{
		Product: NewProductHandler(db),
		Session: NewSessionHandler(db),
		User:    NewUserHandler(db),
	}
}

// Mount attaches every entity's routes onto the given router. Call this with
// the app itself (routes at root) or a group such as app.Group("/admin").
// It also registers the framework-level admin.entities catalog route.
func (a *Admin) Mount(r fiber.Router) {
	a.Product.Register(r)
	a.Session.Register(r)
	a.User.Register(r)
	r.Post("/admin.entities", a.entities)
}

// entities serves the admin.entities catalog — one Metadata entry per
// registered handler, each with its Path / MetadataPath rewritten to be
// absolute for the current request.
func (a *Admin) entities(c *fiber.Ctx) error {
	base := runtime.RequestBase(c)
	return c.JSON(fiber.Map{"data": runtime.Catalog{
		Entities: []runtime.Metadata{
			a.Product.BuildMetadata(base),
			a.Session.BuildMetadata(base),
			a.User.BuildMetadata(base),
		},
	}})
}
