// Code generated by admin-gen. DO NOT EDIT.
package admin

import (
	"encoding/json"
	"errors"

	"github.com/gofiber/fiber/v2"
	"github.com/google/uuid"
	"gorm.io/gorm"

	"github.com/hokkung/go-admin/admin-gen/runtime"
	"github.com/hokkung/go-admin/example/cmd/admin-gen/models"
)

// SessionHandler serves POST /session.<action> routes backed by GORM.
// One-file-per-entity by design: handlers, routing, and filter/sort
// allowlists live together so you can trace a request end-to-end in a single
// tab.
type SessionHandler struct {
	db *gorm.DB
	// idGenerator mints an id when create is called with the zero value.
	// Default is nil (DB auto-increment) except for UUID entities, where
	// the constructor seeds it with uuid.New so existing behavior is
	// preserved. Override via SetIDGenerator.
	idGenerator func() uuid.UUID
	// actions holds fiber handlers for //admin:action-declared custom
	// actions, keyed by action name. Populated at runtime via OnAction.
	actions map[string]fiber.Handler
}

func NewSessionHandler(db *gorm.DB) *SessionHandler {
	return &SessionHandler{
		db:          db,
		idGenerator: func() uuid.UUID { return uuid.New() },
		actions:     map[string]fiber.Handler{},
	}
}

// SetIDGenerator installs a custom id minter. Called after construction, it
// overrides the default uuid.New seed. The
// function runs only when create receives a zero-valued id, so clients that
// pass their own id still win.
func (h *SessionHandler) SetIDGenerator(fn func() uuid.UUID) {
	h.idGenerator = fn
}

// OnAction wires a fiber handler to a //admin:action-declared action name.
// Panics on unknown names so typos fail loud at startup rather than as a
// 501 on the first client request.
func (h *SessionHandler) OnAction(name string, handler fiber.Handler) {
	if _, ok := sessionKnownActions[name]; !ok {
		panic("session: unknown custom action " + name + " (declared actions: see //admin:action directives above " + "Session)")
	}
	h.actions[name] = handler
}

// Register mounts all session.* routes onto the given router.
func (h *SessionHandler) Register(r fiber.Router) {
	r.Post("/session.create", h.create)
	r.Post("/session.get", h.get)
	r.Post("/session.update", h.update)
	r.Post("/session.delete", h.delete)
	r.Post("/session.list", h.list)
	r.Post("/session.metadata", h.metadata)
}

// sessionKnownActions stays empty when no //admin:action directives
// are declared; OnAction will reject any name passed in. Declared so the
// shape of the generated file is stable across entities.
var sessionKnownActions = map[string]struct{}{}

// ---- create -----------------------------------------------------------

func (h *SessionHandler) create(c *fiber.Ctx) error {
	var entity models.Session
	if len(c.Body()) > 0 {
		if err := json.Unmarshal(c.Body(), &entity); err != nil {
			return runtime.WriteError(c, runtime.BadRequest("invalid json: "+err.Error()))
		}
	}

	if h.idGenerator != nil && isZeroSessionID(entity.ID) {
		entity.ID = h.idGenerator()
	}

	if err := validateSession(&entity); err != nil {
		return runtime.WriteError(c, runtime.ValidationError(err))
	}

	if err := h.db.WithContext(c.Context()).Create(&entity).Error; err != nil {
		return runtime.WriteError(c, err)
	}
	return c.JSON(entity)
}

// ---- get --------------------------------------------------------------

func (h *SessionHandler) get(c *fiber.Ctx) error {
	id, err := decodeSessionID(c.Body())
	if err != nil {
		return runtime.WriteError(c, err)
	}
	var entity models.Session
	if err := h.db.WithContext(c.Context()).First(&entity, "\"id\" = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return runtime.WriteError(c, runtime.ErrNotFound)
		}
		return runtime.WriteError(c, err)
	}
	return c.JSON(entity)
}

// ---- update (partial merge: read, overlay, write) ---------------------

func (h *SessionHandler) update(c *fiber.Ctx) error {
	var raw map[string]json.RawMessage
	if len(c.Body()) > 0 {
		if err := json.Unmarshal(c.Body(), &raw); err != nil {
			return runtime.WriteError(c, runtime.BadRequest("invalid json: "+err.Error()))
		}
	}
	idRaw, ok := raw["id"]
	if !ok {
		return runtime.WriteError(c, runtime.BadRequest("id is required"))
	}
	id, err := decodeSessionIDFromRaw(idRaw)
	if err != nil {
		return runtime.WriteError(c, err)
	}

	var entity models.Session
	if err := h.db.WithContext(c.Context()).First(&entity, "\"id\" = ?", id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return runtime.WriteError(c, runtime.ErrNotFound)
		}
		return runtime.WriteError(c, err)
	}

	delete(raw, "id")
	rebuilt, mErr := json.Marshal(raw)
	if mErr != nil {
		return runtime.WriteError(c, runtime.BadRequest("invalid update body"))
	}
	if err := json.Unmarshal(rebuilt, &entity); err != nil {
		return runtime.WriteError(c, runtime.BadRequest("invalid update body: "+err.Error()))
	}
	entity.ID = id

	if err := validateSession(&entity); err != nil {
		return runtime.WriteError(c, runtime.ValidationError(err))
	}

	if err := h.db.WithContext(c.Context()).Save(&entity).Error; err != nil {
		return runtime.WriteError(c, err)
	}
	return c.JSON(entity)
}

// ---- delete -----------------------------------------------------------

func (h *SessionHandler) delete(c *fiber.Ctx) error {
	id, err := decodeSessionID(c.Body())
	if err != nil {
		return runtime.WriteError(c, err)
	}
	tx := h.db.WithContext(c.Context()).Delete(&models.Session{}, "\"id\" = ?", id)
	if tx.Error != nil {
		return runtime.WriteError(c, tx.Error)
	}
	if tx.RowsAffected == 0 {
		return runtime.WriteError(c, runtime.ErrNotFound)
	}
	return c.JSON(fiber.Map{"deleted": true, "id": id})
}

// ---- list (filter / sort / paginate, all pushed into SQL) -------------

func (h *SessionHandler) list(c *fiber.Ctx) error {
	var q runtime.ListQuery
	if len(c.Body()) > 0 {
		if err := json.Unmarshal(c.Body(), &q); err != nil {
			return runtime.WriteError(c, runtime.BadRequest("invalid json: "+err.Error()))
		}
	}
	runtime.NormalizeQuery(&q, 50, 200)
	if len(q.Sort) == 0 {
		q.Sort = []runtime.SortSpec{{Field: "issued_at", Order: "desc"}}
	}

	tx := h.db.WithContext(c.Context()).Model(&models.Session{})

	for _, f := range q.Filters {
		switch f.Field {
		case "user_email", "issued_at":
			tx = runtime.ApplyGormFilter(tx, f.Field, f)
		default:
			return runtime.WriteError(c, runtime.BadRequest("field not filterable: "+f.Field))
		}
	}

	var total int64
	if err := tx.Session(&gorm.Session{}).Count(&total).Error; err != nil {
		return runtime.WriteError(c, err)
	}

	for _, s := range q.Sort {
		switch s.Field {
		case "issued_at":
			dir := "ASC"
			if s.Order == "desc" {
				dir = "DESC"
			}
			tx = tx.Order("\"" + s.Field + "\" " + dir)
		default:
			return runtime.WriteError(c, runtime.BadRequest("field not sortable: "+s.Field))
		}
	}

	var items []models.Session
	if err := tx.Offset((q.Page - 1) * q.PageSize).Limit(q.PageSize).Find(&items).Error; err != nil {
		return runtime.WriteError(c, err)
	}
	return c.JSON(runtime.ListResult[models.Session]{
		Items:    items,
		Total:    int(total),
		Page:     q.Page,
		PageSize: q.PageSize,
	})
}

// ---- metadata ---------------------------------------------------------

// sessionMetadataBase holds the shape of this entity as computed at
// generation time. BuildMetadata clones it per request and stamps the
// request-absolute Path / MetadataPath so clients see absolute URLs that
// work regardless of how the admin routes are grouped.
var sessionMetadataBase = runtime.Metadata{
	Name:        "session",
	DisplayName: "Session",
	PrimaryKey:  "id",
	Fields: []runtime.FieldMetadata{
		{Name: "id", Type: "string", Primary: true, Readonly: true},
		{Name: "user_email", Type: "string", Filterable: true, Searchable: true},
		{Name: "issued_at", Type: "datetime", Readonly: true, Filterable: true, Sortable: true},
	},
	Actions: runtime.ActionsMetadata{
		Standard: []string{"list", "get", "create", "update", "delete", "metadata"},
	},
	ListConfig: runtime.ListConfig{
		DefaultPageSize: 50,
		MaxPageSize:     200,
		DefaultSort: []string{
			"issued_at:desc",
		},
	},
}

// BuildMetadata returns this entity's metadata with Path / MetadataPath
// filled in relative to base (see runtime.RequestBase). Exported so the
// shared admin.entities catalog can aggregate without reflection.
func (h *SessionHandler) BuildMetadata(base string) runtime.Metadata {
	m := sessionMetadataBase
	m.Path = base + "session.list"
	m.MetadataPath = base + "session.metadata"
	return m
}

func (h *SessionHandler) metadata(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{"data": h.BuildMetadata(runtime.RequestBase(c))})
}

// ---- validation -------------------------------------------------------

// validateSession runs every admin-layer check against e in the order
// the runtime admin package uses: enum allowlists first, then each field's
// Validator (both value and pointer form), then the entity's Validator.
// Non-nil returns become the VALIDATION_FAILED envelope.
func validateSession(e *models.Session) error {
	if err := runtime.CallFieldValidator("id", e.ID, &e.ID); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("user_email", e.UserEmail, &e.UserEmail); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("issued_at", e.IssuedAt, &e.IssuedAt); err != nil {
		return err
	}
	if err := runtime.CallEntityValidator(*e, e); err != nil {
		return err
	}
	return nil
}

// ---- id decoding ------------------------------------------------------

type sessionIDBody struct {
	ID uuid.UUID `json:"id"`
}

func decodeSessionID(body []byte) (uuid.UUID, error) {
	var req sessionIDBody
	if len(body) == 0 {
		return req.ID, runtime.BadRequest("id is required")
	}
	if err := json.Unmarshal(body, &req); err != nil {
		return req.ID, runtime.BadRequest("invalid id: " + err.Error())
	}
	if isZeroSessionID(req.ID) {
		return req.ID, runtime.BadRequest("id is required")
	}
	return req.ID, nil
}

func decodeSessionIDFromRaw(raw json.RawMessage) (uuid.UUID, error) {
	var id uuid.UUID
	if len(raw) == 0 {
		return id, runtime.BadRequest("id is required")
	}
	if err := json.Unmarshal(raw, &id); err != nil {
		return id, runtime.BadRequest("invalid id: " + err.Error())
	}
	return id, nil
}

func isZeroSessionID(id uuid.UUID) bool {
	return id == uuid.Nil
}
