// Package runtime contains the small set of shared types and helpers that
// code generated by admin-gen depends on. Keep it minimal on purpose: the
// whole premise of the generator is that your handlers are plain, readable
// Go that you own — pulling framework behavior into this package defeats
// that.
package runtime

import "github.com/gofiber/fiber/v2"

// Error is the canonical error payload returned by any admin handler.
// Generated handlers never return raw Go errors to the client — they wrap
// them here and hand the result to WriteError.
type Error struct {
	Status  int    `json:"-"`
	Code    string `json:"code"`
	Message string `json:"message"`
}

func (e *Error) Error() string { return e.Message }

func NewError(status int, code, message string) *Error {
	return &Error{Status: status, Code: code, Message: message}
}

var (
	ErrNotFound   = NewError(404, "NOT_FOUND", "resource not found")
	ErrBadRequest = NewError(400, "BAD_REQUEST", "invalid request")
	ErrInternal   = NewError(500, "INTERNAL", "internal error")
)

// NotImplemented is returned by the generated custom-action dispatcher when
// an action was declared (so it's in the metadata and has a route) but no
// handler has been registered via OnAction. 501 rather than 404 so clients
// can distinguish "unknown action" (404) from "server hasn't wired it yet"
// (501).
func NotImplemented(action string) *Error {
	return NewError(501, "NOT_IMPLEMENTED", "action "+action+" has no handler registered")
}

// BadRequest constructs a 400 Error with a caller-supplied message. Useful
// from within generated handlers when validating decoded JSON.
func BadRequest(message string) *Error {
	return NewError(400, "BAD_REQUEST", message)
}

// ValidationError wraps a Go error produced by a Validator implementation
// into the canonical 400 VALIDATION_FAILED envelope.
func ValidationError(err error) *Error {
	return NewError(400, "VALIDATION_FAILED", err.Error())
}

type errorEnvelope struct {
	Error *Error `json:"error"`
}

// WriteError serialises err as the canonical {"error":{...}} envelope. Any
// error value is accepted: *Error passes through intact; anything else is
// coerced to a 500 INTERNAL.
func WriteError(c *fiber.Ctx, err error) error {
	e, ok := err.(*Error)
	if !ok {
		e = &Error{Status: 500, Code: "INTERNAL", Message: err.Error()}
	}
	return c.Status(e.Status).JSON(errorEnvelope{Error: e})
}
