// Code generated by admin-gen. DO NOT EDIT.
package admin

import (
	"encoding/json"
	"errors"

	"github.com/gofiber/fiber/v2"
	"gorm.io/gorm"

	"example.com/fixture/full"
	"github.com/hokkung/go-admin/admin-gen/runtime"
)

// UserHandler serves POST /user.<action> routes backed by GORM.
// One-file-per-entity by design: handlers, routing, and filter/sort
// allowlists live together so you can trace a request end-to-end in a single
// tab.
type UserHandler struct {
	db *gorm.DB
	// idGenerator mints an id when create is called with the zero value.
	// Default is nil (DB auto-increment). Override via SetIDGenerator.
	idGenerator func() uint
	// actions holds fiber handlers for //admin:action-declared custom
	// actions, keyed by action name. Populated at runtime via OnAction.
	actions map[string]fiber.Handler
}

func NewUserHandler(db *gorm.DB) *UserHandler {
	return &UserHandler{
		db:      db,
		actions: map[string]fiber.Handler{},
	}
}

// SetIDGenerator installs a custom id minter. Called after construction, it
// overrides the default (DB auto-increment). The
// function runs only when create receives a zero-valued id, so clients that
// pass their own id still win.
func (h *UserHandler) SetIDGenerator(fn func() uint) {
	h.idGenerator = fn
}

// OnAction wires a fiber handler to a //admin:action-declared action name.
// Panics on unknown names so typos fail loud at startup rather than as a
// 501 on the first client request.
func (h *UserHandler) OnAction(name string, handler fiber.Handler) {
	if _, ok := userKnownActions[name]; !ok {
		panic("user: unknown custom action " + name + " (declared actions: see //admin:action directives above " + "User)")
	}
	h.actions[name] = handler
}

// Register mounts all user.* routes onto the given router.
func (h *UserHandler) Register(r fiber.Router) {
	r.Post("/user.create", h.create)
	r.Post("/user.get", h.get)
	r.Post("/user.update", h.update)
	r.Post("/user.delete", h.delete)
	r.Post("/user.list", h.list)
	r.Post("/user.metadata", h.metadata)
	r.Post("/user.activate", h.dispatchAction("activate"))
	r.Post("/user.purge", h.dispatchAction("purge"))
}

// dispatchAction looks up the handler registered for name via OnAction and
// returns 501 NOT_IMPLEMENTED if the caller forgot to wire one up.
func (h *UserHandler) dispatchAction(name string) fiber.Handler {
	return func(c *fiber.Ctx) error {
		handler, ok := h.actions[name]
		if !ok {
			return runtime.WriteError(c, runtime.NotImplemented(name))
		}
		return handler(c)
	}
}

// userKnownActions is the set of declared custom actions for this
// entity, used by OnAction to reject typos. Generated from //admin:action
// directives.
var userKnownActions = map[string]struct{}{
	"activate": {},
	"purge":    {},
}

// ---- create -----------------------------------------------------------

func (h *UserHandler) create(c *fiber.Ctx) error {
	var entity full.User
	if len(c.Body()) > 0 {
		if err := json.Unmarshal(c.Body(), &entity); err != nil {
			return runtime.WriteError(c, runtime.BadRequest("invalid json: "+err.Error()))
		}
	}

	if h.idGenerator != nil && isZeroUserID(entity.ID) {
		entity.ID = h.idGenerator()
	}

	if err := validateUser(&entity); err != nil {
		return runtime.WriteError(c, runtime.ValidationError(err))
	}

	if err := h.db.WithContext(c.Context()).Create(&entity).Error; err != nil {
		return runtime.WriteError(c, err)
	}
	return c.JSON(entity)
}

// ---- get --------------------------------------------------------------

func (h *UserHandler) get(c *fiber.Ctx) error {
	id, err := decodeUserID(c.Body())
	if err != nil {
		return runtime.WriteError(c, err)
	}
	var entity full.User
	if err := h.db.WithContext(c.Context()).First(&entity, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return runtime.WriteError(c, runtime.ErrNotFound)
		}
		return runtime.WriteError(c, err)
	}
	return c.JSON(entity)
}

// ---- update (partial merge: read, overlay, write) ---------------------

func (h *UserHandler) update(c *fiber.Ctx) error {
	var raw map[string]json.RawMessage
	if len(c.Body()) > 0 {
		if err := json.Unmarshal(c.Body(), &raw); err != nil {
			return runtime.WriteError(c, runtime.BadRequest("invalid json: "+err.Error()))
		}
	}
	idRaw, ok := raw["id"]
	if !ok {
		return runtime.WriteError(c, runtime.BadRequest("id is required"))
	}
	id, err := decodeUserIDFromRaw(idRaw)
	if err != nil {
		return runtime.WriteError(c, err)
	}

	var entity full.User
	if err := h.db.WithContext(c.Context()).First(&entity, id).Error; err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return runtime.WriteError(c, runtime.ErrNotFound)
		}
		return runtime.WriteError(c, err)
	}

	delete(raw, "id")
	rebuilt, mErr := json.Marshal(raw)
	if mErr != nil {
		return runtime.WriteError(c, runtime.BadRequest("invalid update body"))
	}
	if err := json.Unmarshal(rebuilt, &entity); err != nil {
		return runtime.WriteError(c, runtime.BadRequest("invalid update body: "+err.Error()))
	}
	entity.ID = id

	if err := validateUser(&entity); err != nil {
		return runtime.WriteError(c, runtime.ValidationError(err))
	}

	if err := h.db.WithContext(c.Context()).Save(&entity).Error; err != nil {
		return runtime.WriteError(c, err)
	}
	return c.JSON(entity)
}

// ---- delete -----------------------------------------------------------

func (h *UserHandler) delete(c *fiber.Ctx) error {
	id, err := decodeUserID(c.Body())
	if err != nil {
		return runtime.WriteError(c, err)
	}
	tx := h.db.WithContext(c.Context()).Delete(&full.User{}, id)
	if tx.Error != nil {
		return runtime.WriteError(c, tx.Error)
	}
	if tx.RowsAffected == 0 {
		return runtime.WriteError(c, runtime.ErrNotFound)
	}
	return c.JSON(fiber.Map{"deleted": true, "id": id})
}

// ---- list (filter / sort / paginate, all pushed into SQL) -------------

func (h *UserHandler) list(c *fiber.Ctx) error {
	var q runtime.ListQuery
	if len(c.Body()) > 0 {
		if err := json.Unmarshal(c.Body(), &q); err != nil {
			return runtime.WriteError(c, runtime.BadRequest("invalid json: "+err.Error()))
		}
	}
	runtime.NormalizeQuery(&q, 25, 200)
	if len(q.Sort) == 0 {
		q.Sort = []runtime.SortSpec{{Field: "created_at", Order: "desc"}}
	}

	tx := h.db.WithContext(c.Context()).Model(&full.User{})

	for _, f := range q.Filters {
		switch f.Field {
		case "name", "status", "created_at", "updated_at":
			tx = runtime.ApplyGormFilter(tx, f.Field, f)
		default:
			return runtime.WriteError(c, runtime.BadRequest("field not filterable: "+f.Field))
		}
	}

	var total int64
	if err := tx.Session(&gorm.Session{}).Count(&total).Error; err != nil {
		return runtime.WriteError(c, err)
	}

	for _, s := range q.Sort {
		switch s.Field {
		case "id", "name", "created_at", "updated_at":
			dir := "ASC"
			if s.Order == "desc" {
				dir = "DESC"
			}
			tx = tx.Order("\"" + s.Field + "\" " + dir)
		default:
			return runtime.WriteError(c, runtime.BadRequest("field not sortable: "+s.Field))
		}
	}

	var items []full.User
	if err := tx.Offset((q.Page - 1) * q.PageSize).Limit(q.PageSize).Find(&items).Error; err != nil {
		return runtime.WriteError(c, err)
	}
	return c.JSON(runtime.ListResult[full.User]{
		Items:    items,
		Total:    int(total),
		Page:     q.Page,
		PageSize: q.PageSize,
	})
}

// ---- metadata ---------------------------------------------------------

// userMetadataBase holds the shape of this entity as computed at
// generation time. BuildMetadata clones it per request and stamps the
// request-absolute Path / MetadataPath so clients see absolute URLs that
// work regardless of how the admin routes are grouped.
var userMetadataBase = runtime.Metadata{
	Name:        "user",
	DisplayName: "User",
	PrimaryKey:  "id",
	Fields: []runtime.FieldMetadata{
		{Name: "id", Type: "uint", Primary: true, Readonly: true, Sortable: true},
		{Name: "name", Type: "string", Required: true, Filterable: true, Sortable: true, Validation: map[string]any{"maxLength": "255", "minLength": "1"}},
		{Name: "status", Type: "enum", Filterable: true, Options: []string{"active", "inactive"}},
		{Name: "created_at", Type: "datetime", Readonly: true, Filterable: true, Sortable: true},
		{Name: "updated_at", Type: "datetime", Readonly: true, Filterable: true, Sortable: true},
	},
	Actions: runtime.ActionsMetadata{
		Standard: []string{"list", "get", "create", "update", "delete", "metadata"},
		Custom: []runtime.CustomAction{
			{Name: "activate", DisplayName: "Activate User"},
			{Name: "purge", Destructive: true},
		},
	},
	ListConfig: runtime.ListConfig{
		DefaultPageSize: 25,
		MaxPageSize:     200,
		DefaultSort: []string{
			"created_at:desc",
		},
	},
}

// BuildMetadata returns this entity's metadata with Path / MetadataPath
// filled in relative to base (see runtime.RequestBase). Exported so the
// shared admin.entities catalog can aggregate without reflection.
func (h *UserHandler) BuildMetadata(base string) runtime.Metadata {
	m := userMetadataBase
	m.Path = base + "user.list"
	m.MetadataPath = base + "user.metadata"
	return m
}

func (h *UserHandler) metadata(c *fiber.Ctx) error {
	return c.JSON(fiber.Map{"data": h.BuildMetadata(runtime.RequestBase(c))})
}

// ---- validation -------------------------------------------------------

// validateUser runs every admin-layer check against e in the order
// the runtime admin package uses: enum allowlists first, then each field's
// Validator (both value and pointer form), then the entity's Validator.
// Non-nil returns become the VALIDATION_FAILED envelope.
func validateUser(e *full.User) error {
	if err := runtime.EnforceEnum("status", string(e.Status), []string{"active", "inactive"}); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("id", e.ID, &e.ID); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("name", e.Name, &e.Name); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("status", e.Status, &e.Status); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("created_at", e.CreatedAt, &e.CreatedAt); err != nil {
		return err
	}
	if err := runtime.CallFieldValidator("updated_at", e.UpdatedAt, &e.UpdatedAt); err != nil {
		return err
	}
	if err := runtime.CallEntityValidator(*e, e); err != nil {
		return err
	}
	return nil
}

// ---- id decoding ------------------------------------------------------

type userIDBody struct {
	ID uint `json:"id"`
}

func decodeUserID(body []byte) (uint, error) {
	var req userIDBody
	if len(body) == 0 {
		return req.ID, runtime.BadRequest("id is required")
	}
	if err := json.Unmarshal(body, &req); err != nil {
		return req.ID, runtime.BadRequest("invalid id: " + err.Error())
	}
	if isZeroUserID(req.ID) {
		return req.ID, runtime.BadRequest("id is required")
	}
	return req.ID, nil
}

func decodeUserIDFromRaw(raw json.RawMessage) (uint, error) {
	var id uint
	if len(raw) == 0 {
		return id, runtime.BadRequest("id is required")
	}
	if err := json.Unmarshal(raw, &id); err != nil {
		return id, runtime.BadRequest("invalid id: " + err.Error())
	}
	return id, nil
}

func isZeroUserID(id uint) bool {
	return id == 0
}
